{
 "title": "Synchronous vs reactive",
 "description": "Dashboard with research metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Research metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB slowness coefficient (get one) global",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synchronous_db_wait_one_seconds_sum{ used=\"true\"} / on(used) synchronous_controller_one_seconds_sum{ used=\"true\",exception=\"none\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB slowness coefficient (get one) 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(synchronous_db_wait_one_seconds_sum{ instance=\"host.docker.internal:8080\"}[5m]) / on(instance) increase(synchronous_controller_one_seconds_sum{ instance=\"host.docker.internal:8080\",exception=\"none\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB slowness coefficient (get all) global",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synchronous_db_wait_all_seconds_sum{ used=\"true\"} / on(used) synchronous_controller_all_seconds_sum{ used=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB slowness coefficient (get all) 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(synchronous_db_wait_all_seconds_sum{ used=\"true\"}[5m]) / on(used) increase(synchronous_controller_all_seconds_sum{ used=\"true\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB slowness coefficient (get one) 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(synchronous_db_wait_one_seconds_sum{ instance=\"host.docker.internal:8080\"}[5m]) / on(instance) increase(synchronous_controller_one_seconds_sum{ instance=\"host.docker.internal:8080\",exception=\"none\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB slowness coefficient (get all) 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "increase(synchronous_db_wait_all_seconds_sum{ used=\"true\"}[5m]) / on(used) increase(synchronous_controller_all_seconds_sum{ used=\"true\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 14 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg CPU synchronous",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stdev CPU synchronous",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg CPU reactive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stdev CPU reactive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Get one mean process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(synchronous_controller_one_seconds_sum{exception=\"none\"}[5m]) / increase(synchronous_controller_one_seconds_count{exception=\"none\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(reactive_controller_one_seconds_sum[5m]) / increase(reactive_controller_one_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(reactive_first_publish_one_seconds_sum[5m]) / increase(reactive_first_publish_one_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get all mean process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "increase(synchronous_controller_all_seconds_sum[5m]) / increase(synchronous_controller_all_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(reactive_controller_all_seconds_sum[5m]) / increase(reactive_controller_all_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(reactive_first_publish_all_seconds_sum[5m]) / increase(reactive_first_publish_all_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get one mean process time (Syncronous)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(synchronous_controller_one_seconds_sum{exception=\"none\"}[5m]) / increase(synchronous_controller_one_seconds_count{exception=\"none\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get all mean process time (Synchronous)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(synchronous_controller_all_seconds_sum[5m]) / increase(synchronous_controller_all_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get one mean process time (Reactive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(reactive_controller_one_seconds_sum{}[5m]) / increase(reactive_controller_one_seconds_count{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get all mean process time (Reactive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(reactive_controller_all_seconds_sum[5m]) / increase(reactive_controller_all_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}