version: '3.7'

services:
  postgresql:
    image: postgres:15
    container_name: benchmarking-db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - migrations-network
    restart: unless-stopped
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      #- clear-checksums
      - --hub-mode=off #
      - --changelog-file=master.xml #
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://benchmarking-db:5432/postgres
      - --username=root
      - --password=root
      - update #
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - migrations-network
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    networks:
      - metrics-display-network
    volumes:
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
  grafana:
    build: "./config"
    ports:
      - "3000:3000"
    networks:
      - metrics-display-network
    volumes:
      - ./config/grafana:/var/lib/grafana:rw
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root

networks:
  migrations-network:
  metrics-display-network: