server:
  port: 8090
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5440/postgres
    password: root
    username: root
management:
  metrics:
    tags:
      used: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, metric